version: '3.8'
services:
  kafka:
    container_name: turkcell-kafka
    image: bashj79/kafka-kraft
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/opt/kafka/kafka-logs
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    command: start-dev
    volumes:
      - .:/opt/jboss/keycloak/imports
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitor-net
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - grafana_config:/etc/grafana
    networks:
      - monitor-net
  mongodb:
    container_name: turkcell-filterdb-mongodb
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "turkcell"
      MONGO_INITDB_ROOT_PASSWORD: "12345"
    volumes:
      - mongodb_data:/data/db
  mongodbInvoice:
    container_name: turkcell-invoicedb-mongodb
    image: mongo
    command: mongod --port 27018
    ports:
      - "27018:27018"
    volumes:
      - mongodb_data:/data/turkcell-invoicedb
  inventorydb:
    container_name: turkcell-inventorydb-mysql
    image: mysql
    ports:
      - "3307:3307"
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_TCP_PORT=3307
      - VIRTUAL_PORT=3307
    volumes:
      - inventorydb:/data/db
volumes:
  grafana_data:
  grafana_config:
  kafka_data:
  mongodb_data:
  inventorydb:
networks:
  monitor-net:
    driver: bridge