version: '3.8'
services:
  kafka:
    container_name: turkcell-kafka
    image: bashj79/kafka-kraft
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/opt/kafka/kafka-logs
  mongodb:
    container_name: turkcell-filterdb-mongodb
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "turkcell"
      MONGO_INITDB_ROOT_PASSWORD: "12345"
    volumes:
      - mongodb_data:/data/db
  mongodbInvoice:
    container_name: turkcell-invoicedb-mongodb
    image: mongo
    command: mongod --port 27018
    ports:
      - "27018:27018"
    volumes:
      - mongodb_data:/data/turkcell-invoicedb
  inventorydb:
    container_name: turkcell-inventorydb-mysql
    image: mysql
    ports:
      - "3307:3307"
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_TCP_PORT=3307
      - VIRTUAL_PORT=3307
    volumes:
      - inventorydb:/data/db
volumes:
  kafka_data:
  mongodb_data:
  inventorydb:
