version: '3.8'
services:
  kafka:
    container_name: turkcell-kafka
    image: bashj79/kafka-kraft
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/opt/kafka/kafka-logs
  mongodb:
    container_name: turkcell-filterdb-mongodb
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "turkcell"
      MONGO_INITDB_ROOT_PASSWORD: "12345"
    volumes:
      - mongodb_data:/data/db
volumes:
  kafka_data:
  mongodb_data: